### ISSUE TITLE
Save the results as csv file

### ISSUE THREAD

**Issue by w062611** [R3CEPT0R/instagram-scraper#1]
Thanks for your great efforts for this amazing library. I have tried to leverage meta_data() to collect data. But, I was trying to store the collected result as the csv file. 
Here was my approach. 
I tried to use pd.DataFrame to store my collected results and wrote as the csv file. 
But somehow, my csv file contained zero info. 

Is there any way I could save my result as the csv file? 

Thanks a lot!

**Comment by R3CEPT0R** [comment]
Hi w062611,

I haven't been able to get to you as I've been very busy, but I added two methods that create and append the data to a file. It saves it as .txt, but it can be easily changed to csv format by replacing ".txt" with ".csv" on lines 194/197. Alternatively, you can make a new .csv file and utilize the "meta_append" method. Let me know if this solves your issue.

**Comment by w062611** [comment]
You are super awesome! It works. 
Another quick question about the "download_all" method. I was able to download all pics saved in my folder and see the status of each post in my console. Is there any way that I could save all of these statuses into one single output file (e.g., json, csv).  

Thanks again for your great efforts!

**Comment by R3CEPT0R** [comment]
Hi w062611,

I recently updated it. I added a flag for the download_all() method called save. If set to true, it should scrape the information from each post into a file titled <username>_data.txt. You can easily change it to .csv or .json. Currently, it's just the raw data (not properly formatted) in a json format. I'll probably fix that in a future iteration to make it look "pretty". I will also add a method to scrape all comments in a given post/all posts. Hope this fixed your issue.

**Comment by w062611** [comment]
Super awesome! It works. Look forward to the new method of scraping all comments. Thanks again for your great efforts.

**Comment by w062611** [comment]
One more quick question about the download_all() method. I was able to download and save the output in an appropriate format (e.g., csv). Is there anyone I could detect
